### ISSUE TITLE
solid: exports are not defined

### ISSUE THREAD

**Issue by b3nten** [css-hooks/css-hooks#46]
Running into an issue using the solid package with solid start. 

```
[vite] Error when evaluating SSR module /src/modules/style.ts: failed to import "@css-hooks/solid"
|- ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/benten/dev/blog/node_modules/.pnpm/@css-hooks+solid@1.5.1_solid-js@1.8.7/node_modules/@css-hooks/solid/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/benten/dev/blog/node_modules/.pnpm/@css-hooks+solid@1.5.1_solid-js@1.8.7/node_modules/@css-hooks/solid/cjs/index.js:2:23
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async nodeImport (file:///Users/benten/dev/blog/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56097:17)
    at async ssrImport (file:///Users/benten/dev/blog/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55990:24)
    at async eval (/Users/benten/dev/blog/src/modules/style.ts:3:44)
    at async instantiateModule (file:///Users/benten/dev/blog/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9)
```

This can be fixed by adding the following to `@css-hooks/solid`'s `package.json`:
```
"exports": {
    ".": {
      "import": "./esm/index.js",
      "require": "./cjs/index.js"
    }
  }
```

I'm not super familiar with vite or node package resolution, so I'm not sure if this is an issue with this package, or with vite and how it handles server side module resolution and imports.

**Comment by b3nten** [comment]
This is probably not just an issue for the solid package, so perhaps should be applied to all packages in the monorepo.

**Comment by nsaunders** [comment]
Great find! I haven't run across this yet, but it doesn't surprise me and I'd love to get it fixed. Were you working on a PR? (I noticed your fork.)

**Comment by b3nten** [comment]
Yep #47
